version: '3'

services:
  portal:
    build: ./portal
    restart: always
    command: gunicorn portal.wsgi:application --bind 0.0.0.0:8000 --reload 
    volumes:
      - ./portal/:/portal
      - static_volume:/portal/static
    expose:
      - 8000
    env_file:
      - .env
  
  nginx:
    build: ./nginx
    ports:
      - ${PORT_WEB}:80
    volumes:
      - static_volume:/portal/static
    depends_on:
      - portal
  
  # mysql:
  #   image: mysql:5.7
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=app
  #   ports:
  #     - 3366:3306

volumes:
  static_volume:
