version: '3'

services:
  portal:
    build: ./portal
    restart: always
    command: gunicorn portal.wsgi:application --bind 0.0.0.0:8000 --reload 
    volumes:
      - ./portal/:/portal
    expose:
      - 8000
    env_file:
      - .env
  
  nginx:
    build: ./nginx
    ports:
      - ${PORT_WEB}:80
    volumes:
      - ./portal/static/:/portal/static
    depends_on:
      - portal
  
  celery:
    build: ./portal
    command: celery -A portal worker -B -l INFO
    volumes:
      - ./portal/:/portal
    depends_on:
      - portal
      - redis
    env_file:
      - .env
    links:
      - redis

  redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - ${PORT_REDIS}:6379